# Generated by Django 5.2 on 2025-04-17 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prompt_template', models.TextField(help_text='Template with placeholders for AI generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('color', 'Color Picker'), ('image', 'Image Upload'), ('select', 'Select Options'), ('checkbox', 'Checkbox')], max_length=20)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('options', models.TextField(blank=True, help_text='JSON array of options for select fields', null=True)),
                ('required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/')),
                ('html_structure', models.TextField(help_text='Base HTML structure for this template')),
                ('css_structure', models.TextField(help_text='Base CSS for this template')),
                ('js_structure', models.TextField(blank=True, help_text='Base JavaScript for this template', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.websitetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
                ('css_content', models.TextField()),
                ('js_content', models.TextField(blank=True, null=True)),
                ('assets_directory', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated', to='generator.userwebsite')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.customizationfield')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='generator.userwebsite')),
            ],
        ),
        migrations.AddField(
            model_name='customizationfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_fields', to='generator.websitetemplate'),
        ),
    ]
