# Generated by Django 5.2 on 2025-04-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetemplate',
            name='template_type',
            field=models.CharField(choices=[('blog', 'Blog Template'), ('portfolio', 'Portfolio Template'), ('business', 'Business Template'), ('ecommerce', 'E-commerce Template')], default='blog', max_length=20),
        ),
    ]
