# Generated by Django 5.1.7 on 2025-04-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_websitetemplate_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetemplate',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field for template-specific features'),
        ),
        migrations.AddField(
            model_name='websitetemplate',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Whether this is a premium template'),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='template_type',
            field=models.CharField(choices=[('blog', 'Blog Template'), ('portfolio', 'Portfolio Template'), ('business', 'Business Template'), ('ecommerce', 'E-commerce Template'), ('restaurant', 'Restaurant Template'), ('event', 'Event Template'), ('real_estate', 'Real Estate Template'), ('education', 'Education Template'), ('healthcare', 'Healthcare Template'), ('nonprofit', 'Nonprofit Template'), ('personal', 'Personal Template'), ('landing', 'Landing Page Template')], default='blog', max_length=20),
        ),
    ]
