# Generated by Django 5.2 on 2025-04-21 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_add_description_to_userwebsite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedwebsite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='websitecustomization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websitecustomization',
            name='specifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecustomization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='generatedwebsite',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userwebsite',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='userwebsite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='css_structure',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='html_structure',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='js_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websitetemplate',
            name='template_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('portfolio', 'Portfolio'), ('business', 'Business'), ('ecommerce', 'E-commerce')], max_length=20),
        ),
    ]
